### ISSUE TITLE
Make it possible to pass a has-many relationship to query instead of the store directly

### ISSUE THREAD

**Issue by joegaudet** [nickschot/ember-model-select#86]
Hey! Love the work so far, we have implemented something similar on an internal project, but it's unfortunately quite bound to jquery. 

One feature we've used fairly extensively is the ability to query has-many relationships through the ember-data-has-many-query. The reason this is valuable, is usually the root object is used to determine authority over the collection.

I would suggest some facility to pass in a hasMany array and perform the query/filtering operations against it.

```<EmberModelSelect   @options={{this.model.someRelatedRecords}} />```

Is there currently a way to avoid your built-in querying all together and drive the component DDAU?

**Comment by nickschot** [comment]
As you already figured out there is currently no way to do that yet. I haven't used ember-data-has-many-query before, but if the change is as easy as #87 i'd totally be up for adding that in!

**Comment by joegaudet** [comment]
@nickschot yep, should just work, ember-data-has-many-query has the same interface as the store. So it allows you to do the following:

```
user.query('comments', {filter: {draft: true}})
```

**Comment by nickschot** [comment]
Fixed by #87 & released in v1.0.0-beta.2!
